
class Tool:
    def __init__(self,name:str,description:str,func_name:str,return_format:dict) -> None:
        self.name = name
        self.description = description
        self.func_name = func_name
        self.return_format = return_format
    
    def __repr__(self) -> str:
        return f"Tool(name={self.name}, description={self.description}, func_name={self.func_name}, return_format={self.return_format})"

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "description": self.description,
            "func_name": self.func_name,
            "return_format": self.return_format
        }
    @staticmethod
    def from_dict(data: dict) -> 'Tool':
        return Tool(
            name=data.get("name", ""),
            description=data.get("description", ""),
            func_name=data.get("func_name", ""),
            return_format=data.get("return_format", {})
        )
        

def create_tool(name: str, description: str, func_name: str, return_format: dict) -> Tool:
    """Create a Tool object with the given parameters."""
    return Tool(name, description, func_name, return_format)



tools:list[Tool] = [
    create_tool(name="append_event",
                description="Write to Events file if user wants to add a event to his schedule at some DD-MM-YYYY TIME or DD-MM-YYYY your job is to generate the content using query of user and return in return_format only inside ```return_format```", 
                func_name="append_file", 
                return_format={"function":"append_event","file_path": "events.txt","content": "to be added by Jarvis"}),
    create_tool(name="update_event",
                description="Update an event in Events file if user wants to update a event from his schedule at some DD-MM-YYYY TIME or DD-MM-YYYY return in return_format only inside ```return_format```", func_name="update_file", return_format={"function":"update_event","file_path": "events.txt","old_content": "content to be updated","new_content": "new content after update"}),
    create_tool(name="list_files",
                description="List all files in the documents directory if user wants to know what documents are available return in return_format only inside ```return_format```",
                func_name="list_files",
                return_format={"function":"list_files"}),
    create_tool(name="search_internet",
                description="search the internet for relevant documents , Your job is to generate a query that goes to search and return only inside the return_format in json ```return_format```",
                func_name="search_internet",
                return_format={"function":"search_internet","query":"generated by jarvis according to users query"})
]